package com.astral.obelisk;

import javax.swing.JOptionPane;

/**
 *
 * @author Astralsphere Arts
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        Version = "1.0.0";
        com.astral.internal.SQLite.initDB();
        Active = new java.awt.Color(0, 136, 255);
        Hover = new java.awt.Color(0, 165, 255);
        White = new java.awt.Color(255, 255, 255);
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
        Load_New_Invoice();
        if (com.astral.internal.SQLite.firstUse)
            Container_Deck.show(Container, "start");
        else
            Container_Deck.show(Container, "app");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Bar = new javax.swing.JPanel();
        Title_Bar_Logo = new javax.swing.JLabel();
        Window_Title = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Paragraph_A = new javax.swing.JLabel();
        Paragraph_B = new javax.swing.JLabel();
        Owner_Name_Label = new javax.swing.JLabel();
        Owner_Name = new javax.swing.JTextField();
        Business_Name_Label = new javax.swing.JLabel();
        Business_Name = new javax.swing.JTextField();
        Contact_Number_Label = new javax.swing.JLabel();
        Contact_Number = new javax.swing.JTextField();
        Email_Address_Label = new javax.swing.JLabel();
        Email_Address = new javax.swing.JTextField();
        Business_Location_Label = new javax.swing.JLabel();
        Business_Location = new javax.swing.JTextField();
        Finish_Button = new javax.swing.JButton();
        App_Logo = new javax.swing.JLabel();
        Application = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        New_Invoice = new javax.swing.JLabel();
        Product_List = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Content = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obelisk");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/app-icon.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        Title_Bar.setBackground(new java.awt.Color(60, 60, 60));
        Title_Bar.setForeground(new java.awt.Color(142, 142, 142));
        Title_Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Title_BarMouseDragged(evt);
            }
        });
        Title_Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Title_BarMousePressed(evt);
            }
        });

        Title_Bar_Logo.setBackground(new java.awt.Color(60, 60, 60));
        Title_Bar_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Bar_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/title-bar-logo.png"))); // NOI18N
        Title_Bar_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title_Bar_Logo.setOpaque(true);

        Window_Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Window_Title.setForeground(new java.awt.Color(142, 142, 142));
        Window_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Window_Title.setText("O B E L I S K");
        Window_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Window_Title.setPreferredSize(new java.awt.Dimension(142, 16));
        Window_Title.setRequestFocusEnabled(false);

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/close.png"))); // NOI18N
        Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Title_BarLayout = new javax.swing.GroupLayout(Title_Bar);
        Title_Bar.setLayout(Title_BarLayout);
        Title_BarLayout.setHorizontalGroup(
            Title_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addComponent(Title_Bar_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403)
                .addComponent(Window_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Title_BarLayout.setVerticalGroup(
            Title_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addComponent(Title_Bar_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Container.setPreferredSize(new java.awt.Dimension(1000, 574));
        Container.setLayout(new java.awt.CardLayout());

        Welcome.setPreferredSize(new java.awt.Dimension(1000, 574));

        Heading.setFont(new java.awt.Font("Segoe UI Semilight", 1, 30)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Heading.setText("Welcome To Obelisk!");
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Paragraph_A.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        Paragraph_A.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Paragraph_A.setText("Since this is Your First Time using Obelisk,");
        Paragraph_A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Paragraph_B.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        Paragraph_B.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Paragraph_B.setText("We need some Details about You and Your Business to Set Things up for You.");
        Paragraph_B.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Owner_Name_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Owner_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Owner_Name_Label.setText("Your(Owner's) Name");
        Owner_Name_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Owner_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Business_Name_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Business_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Business_Name_Label.setText("Business Name");
        Business_Name_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Business_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Contact_Number_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Contact_Number_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Contact_Number_Label.setText("Contact Number");
        Contact_Number_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Contact_Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contact_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Contact_NumberKeyPressed(evt);
            }
        });

        Email_Address_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Email_Address_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email_Address_Label.setText("Email Address");
        Email_Address_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Email_Address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Business_Location_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Business_Location_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Business_Location_Label.setText("Business Location (Address)");
        Business_Location_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Business_Location.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Finish_Button.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        Finish_Button.setText("Finish");
        Finish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finish_ButtonActionPerformed(evt);
            }
        });

        App_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/app-logo-large.png"))); // NOI18N

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(WelcomeLayout.createSequentialGroup()
                                    .addComponent(Owner_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Owner_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WelcomeLayout.createSequentialGroup()
                                    .addComponent(Email_Address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Email_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WelcomeLayout.createSequentialGroup()
                                    .addComponent(Business_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Business_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WelcomeLayout.createSequentialGroup()
                                    .addComponent(Contact_Number_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Contact_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Paragraph_A, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Paragraph_B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WelcomeLayout.createSequentialGroup()
                                    .addComponent(Business_Location_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Business_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addComponent(App_Logo)
                .addGap(90, 90, 90))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Paragraph_A)
                .addGap(0, 0, 0)
                .addComponent(Paragraph_B)
                .addGap(26, 26, 26)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Owner_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Owner_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Business_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Business_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contact_Number_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contact_Number))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_Address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Business_Location_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Business_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Finish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(App_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        Container.add(Welcome, "start");

        SideBar.setBackground(new java.awt.Color(51, 51, 51));
        SideBar.setPreferredSize(new java.awt.Dimension(44, 574));

        New_Invoice.setBackground(new java.awt.Color(0, 136, 255));
        New_Invoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        New_Invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/invoice.png"))); // NOI18N
        New_Invoice.setToolTipText("Create New Invoice");
        New_Invoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New_Invoice.setOpaque(true);
        New_Invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                New_InvoiceMousePressed(evt);
            }
        });

        Product_List.setBackground(new java.awt.Color(255, 255, 255));
        Product_List.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Product_List.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/products.png"))); // NOI18N
        Product_List.setToolTipText("List of Products");
        Product_List.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Product_List.setOpaque(true);
        Product_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Product_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Product_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Product_ListMousePressed(evt);
            }
        });

        Settings.setBackground(new java.awt.Color(255, 255, 255));
        Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/settings.png"))); // NOI18N
        Settings.setToolTipText("Settings");
        Settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settings.setOpaque(true);
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsMousePressed(evt);
            }
        });

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/about.png"))); // NOI18N
        About.setToolTipText("About Obelisk");
        About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About.setOpaque(true);
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(New_Invoice)
                            .addComponent(Settings))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Product_List, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(About, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(New_Invoice)
                .addGap(18, 18, 18)
                .addComponent(Product_List)
                .addGap(18, 18, 18)
                .addComponent(Settings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(About)
                .addGap(26, 26, 26))
        );

        Content.setPreferredSize(new java.awt.Dimension(954, 574));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ApplicationLayout = new javax.swing.GroupLayout(Application);
        Application.setLayout(ApplicationLayout);
        ApplicationLayout.setHorizontalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ApplicationLayout.setVerticalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Container.add(Application, "app");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Title_BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_BarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Title_BarMousePressed

    private void Title_BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_BarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_Title_BarMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        com.astral.internal.SQLite.closeDB();
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new java.awt.Color(225, 72, 72));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(White);
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        Close.setBackground(new java.awt.Color(225, 48, 48));
    }//GEN-LAST:event_CloseMousePressed

    private void Contact_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Contact_NumberKeyPressed
        String Number = Contact_Number.getText();
        int length = Number.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 10)
            Contact_Number.setEditable(true);
            else
            Contact_Number.setEditable(false);
        } else {
            switch (evt.getExtendedKeyCode()) {
                case java.awt.event.KeyEvent.VK_BACK_SPACE -> Contact_Number.setEditable(true);
                case java.awt.event.KeyEvent.VK_DELETE -> Contact_Number.setEditable(true);
                default -> Contact_Number.setEditable(false);
            }
        }
    }//GEN-LAST:event_Contact_NumberKeyPressed

    private void Finish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finish_ButtonActionPerformed
        String ownerName = Owner_Name.getText();
        String bizName = Business_Name.getText();
        String bizNumber = Contact_Number.getText();
        String bizMail = Email_Address.getText();
        String bizAddress = Business_Location.getText();
        if (ownerName.equals("") || bizName.equals("") || bizNumber.equals("") ||
            bizMail.equals("") || bizAddress.equals(""))
            JOptionPane.showMessageDialog(null, "All Fields are Required to be Filled."
                + " Please Try Again!", "Empty Feilds", JOptionPane.ERROR_MESSAGE);
        else if (bizNumber.length() != 10)
            JOptionPane.showMessageDialog(null, "Contact Number Must be 10 Digit Long. Please"
                + " Try Again!", "Contact Number Too Short", JOptionPane.ERROR_MESSAGE);
        else {
            com.astral.internal.SQLite.setConfigData(ownerName, bizName, bizNumber, bizMail, bizAddress);
            Container_Deck.show(Container, "app");
        }
    }//GEN-LAST:event_Finish_ButtonActionPerformed

    private void New_InvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseClicked
        Load_New_Invoice();
    }//GEN-LAST:event_New_InvoiceMouseClicked

    private void New_InvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseEntered
        Stored = New_Invoice.getBackground();
        New_Invoice.setBackground(Hover);
    }//GEN-LAST:event_New_InvoiceMouseEntered

    private void New_InvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseExited
        New_Invoice.setBackground(Stored);
    }//GEN-LAST:event_New_InvoiceMouseExited

    private void New_InvoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMousePressed
        New_Invoice.setBackground(Active);
        Product_List.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = New_Invoice.getBackground();
    }//GEN-LAST:event_New_InvoiceMousePressed

    private void Product_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseClicked
        Load_Product_List();
    }//GEN-LAST:event_Product_ListMouseClicked

    private void Product_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseEntered
        Stored = Product_List.getBackground();
        Product_List.setBackground(Hover);
    }//GEN-LAST:event_Product_ListMouseEntered

    private void Product_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseExited
        Product_List.setBackground(Stored);
    }//GEN-LAST:event_Product_ListMouseExited

    private void Product_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMousePressed
        Product_List_Icon_Active();
    }//GEN-LAST:event_Product_ListMousePressed

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        Load_Settings();
    }//GEN-LAST:event_SettingsMouseClicked

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        Stored = Settings.getBackground();
        Settings.setBackground(Hover);
    }//GEN-LAST:event_SettingsMouseEntered

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        Settings.setBackground(Stored);
    }//GEN-LAST:event_SettingsMouseExited

    private void SettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMousePressed
        New_Invoice.setBackground(White);
        Product_List.setBackground(White);
        Settings.setBackground(Active);
        About.setBackground(White);
        Stored = Settings.getBackground();
    }//GEN-LAST:event_SettingsMousePressed

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        Content.removeAll();
        com.astral.obelisk.About scene = new About();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        Stored = About.getBackground();
        About.setBackground(Hover);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        About.setBackground(Stored);
    }//GEN-LAST:event_AboutMouseExited

    private void AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMousePressed
        New_Invoice.setBackground(White);
        Product_List.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(Active);
        Stored = About.getBackground();
    }//GEN-LAST:event_AboutMousePressed

    public static void Load_New_Invoice() {
        Content.removeAll();
        com.astral.obelisk.New_Invoice scene = new New_Invoice();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }
    
    public static void Load_Product_List() {
        Content.removeAll();
        com.astral.obelisk.Product_List scene = new Product_List();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }
    
    public static void Load_Settings() {
        Content.removeAll();
        com.astral.obelisk.Settings scene = new Settings();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }
    
    public static void Product_List_Icon_Active() {
        New_Invoice.setBackground(White);
        Product_List.setBackground(Active);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Product_List.getBackground();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatIntelliJLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatIntelliJLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatIntelliJLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatIntelliJLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        javax.swing.UIManager.put("TabbedPane.showTabSeparators", true);
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel About;
    private javax.swing.JLabel App_Logo;
    private javax.swing.JPanel Application;
    private javax.swing.JTextField Business_Location;
    private javax.swing.JLabel Business_Location_Label;
    private javax.swing.JTextField Business_Name;
    private javax.swing.JLabel Business_Name_Label;
    private javax.swing.JLabel Close;
    private javax.swing.JTextField Contact_Number;
    private javax.swing.JLabel Contact_Number_Label;
    private javax.swing.JPanel Container;
    public static javax.swing.JDesktopPane Content;
    private javax.swing.JTextField Email_Address;
    private javax.swing.JLabel Email_Address_Label;
    private javax.swing.JButton Finish_Button;
    private javax.swing.JLabel Heading;
    private static javax.swing.JLabel New_Invoice;
    private javax.swing.JTextField Owner_Name;
    private javax.swing.JLabel Owner_Name_Label;
    private javax.swing.JLabel Paragraph_A;
    private javax.swing.JLabel Paragraph_B;
    private static javax.swing.JLabel Product_List;
    private static javax.swing.JLabel Settings;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel Title_Bar;
    private javax.swing.JLabel Title_Bar_Logo;
    private javax.swing.JPanel Welcome;
    private javax.swing.JLabel Window_Title;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
    private static java.awt.Color Active;
    private static java.awt.Color Hover;
    private static java.awt.Color White;
    private static java.awt.Color Stored;
    public static String Version;
    private int x, y;
}
