package com.astral.invoice;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Astralsphere Arts
 */
public class About extends javax.swing.JPanel {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        App_Logo = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        About_Paragraph = new javax.swing.JLabel();
        App_Logo_Flipped = new javax.swing.JLabel();
        About_Container = new javax.swing.JTabbedPane();
        Authors_Tab = new javax.swing.JPanel();
        Authors_Container = new javax.swing.JScrollPane();
        Authors_Text = new javax.swing.JTextArea();
        License_Tab = new javax.swing.JPanel();
        License_Container = new javax.swing.JScrollPane();
        License_Text = new javax.swing.JTextArea();
        Credits_Tab = new javax.swing.JPanel();
        Credits_Container = new javax.swing.JScrollPane();
        Credits_Text = new javax.swing.JTextArea();

        App_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/app-logo.png"))); // NOI18N

        Heading.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("About Astral Invoice");
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Version.setFont(new java.awt.Font("Segoe UI Semilight", 1, 15)); // NOI18N
        Version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Version.setText("Version " + com.astral.invoice.Main.Version);
        Version.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        About_Paragraph.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        About_Paragraph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About_Paragraph.setText("Astral Invoice is a Software Used For Generating Invoices");

        App_Logo_Flipped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/app-logo-flipped.png"))); // NOI18N

        About_Container.setPreferredSize(new java.awt.Dimension(639, 360));
        About_Container.putClientProperty( "JTabbedPane.tabAreaAlignment", "center" );

        Authors_Tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        Authors_Container.setBorder(null);

        Authors_Text.setEditable(false);
        Authors_Text.setBackground(new java.awt.Color(255, 255, 255));
        Authors_Text.setColumns(20);
        Authors_Text.setRows(5);
        Authors_Caret = (javax.swing.text.DefaultCaret)License_Text.getCaret();
        Authors_Caret.setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);
        try {
            Authors_Reader = new java.io.BufferedReader(new java.io.InputStreamReader(getClass().getResourceAsStream("/com/astral/resources/authors.txt")));
            Authors_Line = Authors_Reader.readLine();
            while (Authors_Line != null) {
                Authors_Text.append(Authors_Line + "\n");
                Authors_Line = Authors_Reader.readLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        Authors_Container.setViewportView(Authors_Text);

        javax.swing.GroupLayout Authors_TabLayout = new javax.swing.GroupLayout(Authors_Tab);
        Authors_Tab.setLayout(Authors_TabLayout);
        Authors_TabLayout.setHorizontalGroup(
            Authors_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        Authors_TabLayout.setVerticalGroup(
            Authors_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        About_Container.addTab("Authors", Authors_Tab);

        License_Tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        License_Container.setBorder(null);

        License_Text.setEditable(false);
        License_Text.setBackground(new java.awt.Color(255, 255, 255));
        License_Text.setColumns(20);
        License_Text.setRows(5);
        License_Caret = (javax.swing.text.DefaultCaret)License_Text.getCaret();
        License_Caret.setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);
        try {
            License_Reader = new java.io.BufferedReader(new java.io.InputStreamReader(getClass().getResourceAsStream("/com/astral/resources/license.txt")));
            License_Line = License_Reader.readLine();
            while (License_Line != null) {
                License_Text.append(License_Line + "\n");
                License_Line = License_Reader.readLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        License_Container.setViewportView(License_Text);

        javax.swing.GroupLayout License_TabLayout = new javax.swing.GroupLayout(License_Tab);
        License_Tab.setLayout(License_TabLayout);
        License_TabLayout.setHorizontalGroup(
            License_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(License_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        License_TabLayout.setVerticalGroup(
            License_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(License_Container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        About_Container.addTab("License", License_Tab);

        Credits_Tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        Credits_Container.setBorder(null);

        Credits_Text.setEditable(false);
        Credits_Text.setBackground(new java.awt.Color(255, 255, 255));
        Credits_Text.setColumns(20);
        Credits_Text.setRows(5);
        Credits_Caret = (javax.swing.text.DefaultCaret)License_Text.getCaret();
        Credits_Caret.setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);
        try {
            Credits_Reader = new java.io.BufferedReader(new java.io.InputStreamReader(getClass().getResourceAsStream("/com/astral/resources/credits.txt")));
            Credits_Line = Credits_Reader.readLine();
            while (Credits_Line != null) {
                Credits_Text.append(Credits_Line + "\n");
                Credits_Line = Credits_Reader.readLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        Credits_Container.setViewportView(Credits_Text);

        javax.swing.GroupLayout Credits_TabLayout = new javax.swing.GroupLayout(Credits_Tab);
        Credits_Tab.setLayout(Credits_TabLayout);
        Credits_TabLayout.setHorizontalGroup(
            Credits_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Credits_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        Credits_TabLayout.setVerticalGroup(
            Credits_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Credits_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        About_Container.addTab("Credits", Credits_Tab);

        About_Container.setSelectedComponent(License_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(About_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(App_Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Version, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(About_Paragraph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(App_Logo_Flipped)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Version)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(About_Paragraph))
                        .addComponent(App_Logo_Flipped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(App_Logo))
                .addGap(26, 26, 26)
                .addComponent(About_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane About_Container;
    private javax.swing.JLabel About_Paragraph;
    private javax.swing.JLabel App_Logo;
    private javax.swing.JLabel App_Logo_Flipped;
    private javax.swing.JScrollPane Authors_Container;
    private javax.swing.JPanel Authors_Tab;
    private javax.swing.JTextArea Authors_Text;
    private javax.swing.JScrollPane Credits_Container;
    private javax.swing.JPanel Credits_Tab;
    private javax.swing.JTextArea Credits_Text;
    private javax.swing.JLabel Heading;
    private javax.swing.JScrollPane License_Container;
    private javax.swing.JPanel License_Tab;
    private javax.swing.JTextArea License_Text;
    private javax.swing.JLabel Version;
    // End of variables declaration//GEN-END:variables
    private javax.swing.text.DefaultCaret Authors_Caret;
    private javax.swing.text.DefaultCaret Credits_Caret;
    private javax.swing.text.DefaultCaret License_Caret;
    private java.io.BufferedReader Authors_Reader;
    private java.io.BufferedReader Credits_Reader;
    private java.io.BufferedReader License_Reader;
    private String Authors_Line;
    private String Credits_Line;
    private String License_Line;
}
