package com.astral.invoice;

/**
 *
 * @author Astralsphere Arts
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        Version = "0.2-alpha";
        com.astral.internal.SQLite.initDB();
        Active = new java.awt.Color(0, 136, 255);
        Hover = new java.awt.Color(0, 165, 255);
        White = new java.awt.Color(255, 255, 255);
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
        com.astral.invoice.New_Invoice scene = new New_Invoice();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
        if (com.astral.internal.SQLite.firstUse)
            Container_Deck.show(Container, "start");
        else
            Container_Deck.show(Container, "app");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Bar = new javax.swing.JPanel();
        Title_Bar_Logo = new javax.swing.JLabel();
        Window_Title = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        OK_Button = new javax.swing.JButton();
        Application = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        New_Invoice = new javax.swing.JLabel();
        Product_List = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Help = new javax.swing.JLabel();
        Content = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Astral Invoice");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/app-icon.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        Title_Bar.setBackground(new java.awt.Color(60, 60, 60));
        Title_Bar.setForeground(new java.awt.Color(142, 142, 142));
        Title_Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Title_BarMouseDragged(evt);
            }
        });
        Title_Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Title_BarMousePressed(evt);
            }
        });

        Title_Bar_Logo.setBackground(new java.awt.Color(60, 60, 60));
        Title_Bar_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Bar_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/title-bar-logo.png"))); // NOI18N
        Title_Bar_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title_Bar_Logo.setOpaque(true);

        Window_Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Window_Title.setForeground(new java.awt.Color(142, 142, 142));
        Window_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Window_Title.setText("A S T R A L    I N V O I C E");
        Window_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Window_Title.setPreferredSize(new java.awt.Dimension(142, 16));
        Window_Title.setRequestFocusEnabled(false);

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/close.png"))); // NOI18N
        Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Title_BarLayout = new javax.swing.GroupLayout(Title_Bar);
        Title_Bar.setLayout(Title_BarLayout);
        Title_BarLayout.setHorizontalGroup(
            Title_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addComponent(Title_Bar_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403)
                .addComponent(Window_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Title_BarLayout.setVerticalGroup(
            Title_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Title_BarLayout.createSequentialGroup()
                .addComponent(Title_Bar_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Container.setPreferredSize(new java.awt.Dimension(1000, 574));
        Container.setLayout(new java.awt.CardLayout());

        OK_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        OK_Button.setText("OK");
        OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                .addContainerGap(498, Short.MAX_VALUE)
                .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        Container.add(Welcome, "start");

        SideBar.setBackground(new java.awt.Color(51, 51, 51));
        SideBar.setPreferredSize(new java.awt.Dimension(44, 574));

        New_Invoice.setBackground(new java.awt.Color(0, 136, 255));
        New_Invoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        New_Invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/invoice.png"))); // NOI18N
        New_Invoice.setToolTipText("Create New Invoice");
        New_Invoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New_Invoice.setOpaque(true);
        New_Invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_InvoiceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                New_InvoiceMousePressed(evt);
            }
        });

        Product_List.setBackground(new java.awt.Color(255, 255, 255));
        Product_List.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Product_List.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/products.png"))); // NOI18N
        Product_List.setToolTipText("List of Products");
        Product_List.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Product_List.setOpaque(true);
        Product_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Product_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Product_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Product_ListMousePressed(evt);
            }
        });

        Settings.setBackground(new java.awt.Color(255, 255, 255));
        Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/settings.png"))); // NOI18N
        Settings.setToolTipText("Settings");
        Settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settings.setOpaque(true);
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsMousePressed(evt);
            }
        });

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/about.png"))); // NOI18N
        About.setToolTipText("About Astral Invoice");
        About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About.setOpaque(true);
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMousePressed(evt);
            }
        });

        Help.setBackground(new java.awt.Color(255, 255, 255));
        Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/astral/resources/help.png"))); // NOI18N
        Help.setToolTipText("Help");
        Help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Help.setOpaque(true);
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HelpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HelpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(New_Invoice)
                            .addComponent(Settings)
                            .addComponent(Help))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Product_List, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(About, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(New_Invoice)
                .addGap(18, 18, 18)
                .addComponent(Product_List)
                .addGap(18, 18, 18)
                .addComponent(Settings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(About)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Help)
                .addGap(26, 26, 26))
        );

        Content.setPreferredSize(new java.awt.Dimension(954, 574));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ApplicationLayout = new javax.swing.GroupLayout(Application);
        Application.setLayout(ApplicationLayout);
        ApplicationLayout.setHorizontalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ApplicationLayout.setVerticalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Container.add(Application, "app");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Title_BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_BarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Title_BarMousePressed

    private void Title_BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title_BarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_Title_BarMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        com.astral.internal.SQLite.closeDB();
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new java.awt.Color(225, 72, 72));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(White);
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        Close.setBackground(new java.awt.Color(225, 48, 48));
    }//GEN-LAST:event_CloseMousePressed

    private void OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_ButtonActionPerformed
        Container_Deck.show(Container, "app");
    }//GEN-LAST:event_OK_ButtonActionPerformed

    private void New_InvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseClicked
        Content.removeAll();
        com.astral.invoice.New_Invoice scene = new New_Invoice();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_New_InvoiceMouseClicked

    private void New_InvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseEntered
        Stored = New_Invoice.getBackground();
        New_Invoice.setBackground(Hover);
    }//GEN-LAST:event_New_InvoiceMouseEntered

    private void New_InvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMouseExited
        New_Invoice.setBackground(Stored);
    }//GEN-LAST:event_New_InvoiceMouseExited

    private void New_InvoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_InvoiceMousePressed
        New_Invoice.setBackground(Active);
        Product_List.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Help.setBackground(White);
        Stored = New_Invoice.getBackground();
    }//GEN-LAST:event_New_InvoiceMousePressed
    
    public static void Product_List_Edit_ActionPerformed() {
        New_Invoice.setBackground(White);
        Product_List.setBackground(Active);
        Settings.setBackground(White);
        About.setBackground(White);
        Help.setBackground(White);
        Stored = Product_List.getBackground();
    }

    private void Product_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseClicked
        Content.removeAll();
        com.astral.invoice.Product_List scene = new Product_List();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_Product_ListMouseClicked

    private void Product_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseEntered
        Stored = Product_List.getBackground();
        Product_List.setBackground(Hover);
    }//GEN-LAST:event_Product_ListMouseEntered

    private void Product_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMouseExited
        Product_List.setBackground(Stored);
    }//GEN-LAST:event_Product_ListMouseExited

    private void Product_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ListMousePressed
        Product_List_Edit_ActionPerformed();
    }//GEN-LAST:event_Product_ListMousePressed

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        Stored = Settings.getBackground();
        Settings.setBackground(Hover);
    }//GEN-LAST:event_SettingsMouseEntered

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        Settings.setBackground(Stored);
    }//GEN-LAST:event_SettingsMouseExited

    private void SettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMousePressed
        New_Invoice.setBackground(White);
        Product_List.setBackground(White);
        Settings.setBackground(Active);
        About.setBackground(White);
        Help.setBackground(White);
        Stored = Settings.getBackground();
    }//GEN-LAST:event_SettingsMousePressed

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        Content.removeAll();
        com.astral.invoice.About scene = new About();
        scene.setBounds(0, 0, 954, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        Stored = About.getBackground();
        About.setBackground(Hover);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        About.setBackground(Stored);
    }//GEN-LAST:event_AboutMouseExited

    private void AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMousePressed
        New_Invoice.setBackground(White);
        Product_List.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(Active);
        Help.setBackground(White);
        Stored = About.getBackground();
    }//GEN-LAST:event_AboutMousePressed

    private void HelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseEntered
        Stored = Help.getBackground();
        Help.setBackground(Hover);
    }//GEN-LAST:event_HelpMouseEntered

    private void HelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseExited
        Help.setBackground(Stored);
    }//GEN-LAST:event_HelpMouseExited

    private void HelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMousePressed
        New_Invoice.setBackground(White);
        Product_List.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Help.setBackground(Active);
        Stored = Help.getBackground();
    }//GEN-LAST:event_HelpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatIntelliJLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatIntelliJLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatIntelliJLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatIntelliJLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        javax.swing.UIManager.put("TabbedPane.showTabSeparators", true);
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel About;
    private javax.swing.JPanel Application;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel Container;
    public static javax.swing.JDesktopPane Content;
    private static javax.swing.JLabel Help;
    private static javax.swing.JLabel New_Invoice;
    private javax.swing.JButton OK_Button;
    private static javax.swing.JLabel Product_List;
    private static javax.swing.JLabel Settings;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel Title_Bar;
    private javax.swing.JLabel Title_Bar_Logo;
    private javax.swing.JPanel Welcome;
    private javax.swing.JLabel Window_Title;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
    private static java.awt.Color Active;
    private static java.awt.Color Hover;
    private static java.awt.Color White;
    private static java.awt.Color Stored;
    public static String Version;
    private int x, y;
}
